FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

# install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip git ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt

RUN pip3 install --upgrade pip && \
    pip3 install --index-url https://download.pytorch.org/whl/cu121 \
      torch torchvision torchaudio && \
    pip3 install -r /app/requirements.txt

# Copy project
COPY . /app

# cache folder mount
ENV HF_HOME=/data/hf_cache
RUN mkdir -p /data/hf_cache

# ENV HF_HOME=/hf_cache
# ENV HF_HUB_CACHE=/hf_cache
# RUN mkdir -p /data/hf_cache

CMD ["python3", "benchmark.py"]
